# Generated by Django 6.0.4 on 2026-06-01 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jops_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_title', models.CharField(blank=True, help_text='Job Title', max_length=100, null=True)),
                ('j_description', models.TextField(blank=True, help_text='Job Description', null=True)),
                ('j_location', models.CharField(blank=True, help_text='Job Location', max_length=100, null=True)),
                ('j_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Job Salary', max_digits=10, null=True)),
                ('j_posted', models.DateField(auto_now_add=True, help_text='Job Posted Date')),
                ('j_active', models.BooleanField(default=False, help_text='Job Active')),
                ('j_logo', models.ImageField(blank=True, help_text='Job Logo', max_length=200, null=True, upload_to='static/job_logos/')),
                ('j_jobtype', models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], help_text='Job Type', max_length=20, null=True)),
                ('j_EXP', models.DateField(help_text='Job Experience')),
                ('j_company', models.ForeignKey(help_text='Company', on_delete=django.db.models.deletion.CASCADE, to='companyapp.company_db')),
            ],
            options={
                'verbose_name': 'SHaqo',
                'verbose_name_plural': 'SHaqoyin',
            },
        ),
    ]
