# Generated by Django 6.0.4 on 2026-06-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jops_db',
            name='j_posted',
            field=models.DateTimeField(auto_now_add=True, help_text='Job Posted Date'),
        ),
    ]
