# Generated by Django 6.0.4 on 2026-04-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jops_db',
            options={'verbose_name': 'SHaqo', 'verbose_name_plural': 'SHaqoyin'},
        ),
    ]
