# Generated by Django 6.0.4 on 2026-06-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shaqod_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_fullname', models.CharField(help_text='Full Name', max_length=100)),
                ('s_email', models.EmailField(help_text='Email', max_length=254, unique=True)),
                ('s_username', models.CharField(help_text='Username', max_length=100, unique=True)),
                ('s_password', models.CharField(help_text='Password', max_length=100)),
                ('s_phone', models.CharField(blank=True, help_text='Phone', max_length=15, null=True, unique=True)),
                ('s_profile_img', models.ImageField(blank=True, help_text='Profile Image', null=True, upload_to='static/profile/')),
                ('s_status', models.BooleanField(default=True)),
                ('s_geneder', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('s_created', models.DateTimeField(auto_now_add=True, help_text='Created Date')),
            ],
            options={
                'verbose_name': 'Shaqodon',
                'verbose_name_plural': 'Shaqodonayal',
            },
        ),
    ]
