# Generated by Django 6.0.4 on 2026-06-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaqodonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shaqod_db',
            name='s_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shaqod_db',
            name='s_cv',
            field=models.FileField(blank=True, null=True, upload_to='shaqodonapp/cv/'),
        ),
        migrations.AddField(
            model_name='shaqod_db',
            name='s_education',
            field=models.CharField(blank=True, choices=[('High School', 'High School'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD'), ('Other', 'Other'), ('Experience', 'Experience')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shaqod_db',
            name='s_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shaqod_db',
            name='s_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shaqod_db',
            name='s_profile_img',
            field=models.ImageField(blank=True, help_text='Profile Image', null=True, upload_to='shaqodonapp/profile/'),
        ),
    ]
