# Generated by Django 6.0.4 on 2026-04-24 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobsapp', '0002_alter_jops_db_options'),
        ('shaqodonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_cv', models.FileField(help_text='Upload CV', upload_to='static/cv/')),
                ('a_cover_letter', models.TextField(blank=True, help_text='Cover Letter', null=True)),
                ('a_applied_date', models.DateTimeField(auto_now_add=True, help_text='Application Date')),
                ('a_current_location', models.CharField(blank=True, help_text='Current Location', max_length=100, null=True)),
                ('a_status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('a_job', models.ForeignKey(help_text='Job Title', on_delete=django.db.models.deletion.CASCADE, to='jobsapp.jops_db')),
                ('a_shaqod', models.ForeignKey(help_text='Shaqod Qofka', on_delete=django.db.models.deletion.CASCADE, to='shaqodonapp.shaqod_db')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
