# Generated by Django 5.2.8 on 2026-05-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_db',
            name='a_deleted_by_company',
            field=models.BooleanField(default=False, help_text='Company soft-deleted this application (hidden from company view only)'),
        ),
        migrations.AlterField(
            model_name='application_db',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
