# Generated by Django 6.0.4 on 2026-06-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, help_text='Company Name', max_length=100, null=True)),
                ('c_description', models.TextField(blank=True, help_text='Company Description', null=True)),
                ('c_email', models.EmailField(blank=True, help_text='Company Email', max_length=254, null=True, unique=True)),
                ('c_phone', models.CharField(blank=True, help_text='Company Phone', max_length=15, null=True)),
                ('c_username', models.CharField(blank=True, help_text='Company Username', max_length=100, null=True)),
                ('c_password', models.CharField(blank=True, help_text='Company Password', max_length=100, null=True)),
                ('c_joined', models.DateField(auto_now_add=True, help_text='Company Joined Date')),
                ('c_logo', models.ImageField(blank=True, help_text='Company Logo', max_length=200, null=True, upload_to='static/company_logos/')),
                ('c_active', models.BooleanField(default=False, help_text='Company Active')),
            ],
            options={
                'verbose_name': 'Combani',
                'verbose_name_plural': 'combaniyo',
                'unique_together': {('c_username', 'c_email')},
            },
        ),
    ]
