# Generated by Django 6.0.4 on 2026-06-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_db',
            name='c_company_lence',
            field=models.ImageField(blank=True, help_text='Company_geverment_lencec', max_length=200, null=True, upload_to='companyapp/company_lencec/'),
        ),
        migrations.AddField(
            model_name='company_db',
            name='c_header_location',
            field=models.CharField(blank=True, help_text='Company Header Location', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company_db',
            name='c_verivaed',
            field=models.BooleanField(default=False, help_text='Company Verified'),
        ),
    ]
