# Generated by Django 6.0.4 on 2026-06-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0002_company_db_c_company_lence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_db',
            name='c_contect_address',
            field=models.CharField(blank=True, help_text='Company Contect Address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company_db',
            name='c_facebook_page',
            field=models.URLField(blank=True, help_text='Company Facebook Page', null=True),
        ),
        migrations.AddField(
            model_name='company_db',
            name='c_instegram_page',
            field=models.URLField(blank=True, help_text='Company Instegram Page', null=True),
        ),
        migrations.AddField(
            model_name='company_db',
            name='c_linkdin_page',
            field=models.URLField(blank=True, help_text='Company Linkdin Page', null=True),
        ),
        migrations.AddField(
            model_name='company_db',
            name='c_owner_person',
            field=models.CharField(blank=True, help_text='Company Owner Person', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company_db',
            name='c_owner_person_email',
            field=models.EmailField(blank=True, help_text='Company Owner Person Email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company_db',
            name='c_owner_person_fullName',
            field=models.CharField(blank=True, help_text='Company Owner Person Full Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company_db',
            name='c_owner_person_phone',
            field=models.CharField(blank=True, help_text='Company Owner Person Phone', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='company_db',
            name='c_telegram_page',
            field=models.URLField(blank=True, help_text='Company Telegram Page', null=True),
        ),
        migrations.AddField(
            model_name='company_db',
            name='c_twitter_page',
            field=models.URLField(blank=True, help_text='Company Twitter Page', null=True),
        ),
        migrations.AddField(
            model_name='company_db',
            name='c_wbsite',
            field=models.URLField(blank=True, help_text='Company Website', null=True),
        ),
        migrations.AddField(
            model_name='company_db',
            name='c_whatsapp_page',
            field=models.URLField(blank=True, help_text='Company Whatsapp Page', null=True),
        ),
        migrations.AddField(
            model_name='company_db',
            name='c_youtube_page',
            field=models.URLField(blank=True, help_text='Company Youtube Page', null=True),
        ),
        migrations.AlterField(
            model_name='company_db',
            name='c_company_lence',
            field=models.ImageField(blank=True, help_text='Company_geverment_lencec', max_length=200, null=True, upload_to='static/company_logos/'),
        ),
        migrations.AlterField(
            model_name='company_db',
            name='c_header_location',
            field=models.CharField(blank=True, help_text='Company Header Location', max_length=100, null=True),
        ),
    ]
