# Generated by Django 6.0.4 on 2026-06-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0003_company_db_c_contect_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_db',
            name='c_owner_person_docoment',
            field=models.FileField(blank=True, help_text='uploud like somali nira card or ather docoments that goverment recognized', max_length=200, null=True, upload_to='static/company_logos/'),
        ),
    ]
